site_name: The MES College Alumni Association &#174;
site_url: https://mesalumniassociation.com/

theme:
  name: material
  palette:
    primary: teal
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.top
  plugins:
    - search
  # 404 page
  static_templates:
    - 404.html

copyright: Copyright &copy; 2021 The MES College Alumni Association &#174;
repo_url: https://github.com/MESAlumniAssn/docs
repo_name: MESAlumniAssn/docs

nav:
  - Home: "index.md"
  - Architecture: "architecture.md"
  - Developer Workflow: "workflow.md"
  - Project Setup: "setup.md"
  - Database: "database.md"
  - Documentation Changes: "documentation.md"
  - "Website":
      - Project Structure: "website/site_structure.md"
      - Environment Variables: "website/environment.md"
      - Styling: "website/site_style.md"
      - Navbar: "website/navbar.md"
      - Registration & Payments: "website/registration_payments.md"
      - Image Gallery: "website/gallery.md"
      - Admin Dashboard: "website/admin_dashboard.md"
      - Update Association Data: "website/data_update.md"
      - Association Members: "website/members.md"
      - Famous Alumni: "website/famous_alumni.md"
      - Testimonials: "website/testimonials.md"
      - Renewals: "website/renewals.md"
  - "API":
      - Project Structure: "api/api_structure.md"
      - Environment Variables: "api/environment.md"
      - Routers: "api/routers.md"
  - "Jobs":
      - Introduction: "jobs/introduction.md"
      - Birthday Notifications: "jobs/birthdays.md"
      - Expiry Notifications: "jobs/expiry_notifications.md"
      - Renewal Reminders: "jobs/renewal_reminders.md"
      - Database Backup: "jobs/database_backup.md"
  - "How To":
      - Introduction: "how_to/introduction.md"
      - Create Event: "how_to/events.md"
      - Update Gallery: "how_to/gallery.md"
      - Create Blog Post: "how_to/blog.md"
      - Modify Emails: "how_to/emails.md"
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - toc:
      permalink: true

extra_css:
  - stylesheets/styles.css
