site_name: The MES College Alumni Association &#174;
site_url: https://mesalumniassociation.com/

theme:
  name: material
  palette:
    primary: blue grey
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.top
  plugins:
    - search
  # 404 page
  static_templates:
    - 404.html

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
