site_name: The MES College Alumni Association &#174;
site_url: https://mesalumniassociation.com/

theme:
  name: material
  palette:
    primary: teal
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.top
  plugins:
    - search
  # 404 page
  static_templates:
    - 404.html

copyright: Copyright &copy; 2021 The MES College Alumni Association &#174;
repo_url: https://github.com/MESAlumniAssn/docs
repo_name: MESAlumniAssn/docs

nav:
  - Home: "index.md"
  - Architecture: "architecture.md"
  - Developer Workflow: "workflow.md"
  - Project Setup: "setup.md"
  - Documentation Changes: "documentation.md"
  - "Website":
      - Project Structure: "website/site_structure.md"
      - Styling: "website/site_style.md"
      - Navbar: "website/navbar.md"
      - Registration & Payments: "website/registration_payments.md"
      - Admin Dashboard: "website/admin_dashboard.md"

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - toc:
      permalink: true

extra_css:
  - stylesheets/styles.css
